remote_theme: aron-bordin/neo-hpstr-jekyll-theme@1.0.1
plugins:
- jekyll-remote-theme
title: Matt Morehouse
description: Bitcoin Lightning Engineer
show_downloads: false
github:
  repository_url: https://github.com/morehouse
